### ISSUE TITLE
CDI: programmatic lookup problem detected

### ISSUE THREAD

**Issue by TiomanGally** [smallrye/smallrye-context-propagation#363]
Hello 👋🏻

I am writing an application using quarkus with following features:

```
Installed features: [cdi, hibernate-orm, hibernate-reactive, hibernate-reactive-panache, kotlin, reactive-pg-client, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, vertx]
```

The application is a simple CRUD application. Everytime I execute the a REST Request this will be logged:

```
================================================================================
CDI: programmatic lookup problem detected
-----------------------------------------
At least one bean matched the required type and qualifiers but was marked as unused and removed during build

Stack frame: io.smallrye.context.jta.context.propagation.JtaContextProvider.tm(JtaContextProvider.java:119)
Required type: class io.smallrye.context.jta.context.propagation.JtaContextProvider$LifecycleManager
Required qualifiers: [@javax.enterprise.inject.Default()]
Removed beans:
        - CLASS bean  [types=[class io.smallrye.context.jta.context.propagation.JtaContextProvider$LifecycleManager], qualifiers=null]
Solutions:
        - Application developers can eliminate false positives via the @Unremovable annotation
        - Extensions can eliminate false positives via build items, e.g. using the UnremovableBeanBuildItem
        - See also https://quarkus.io/guides/cdi-reference#remove_unused_beans
        - Enable the DEBUG log level to see the full stack trace
================================================================================
```

**Comment by TiomanGally** [comment]
If you want to reproduce it:

1. quarkus create app for.demo:purpose:1.0 --kotlin --gradle-kotlin-dsl --java=17
2. quarkus ext rm quarkus-resteasy
3. quarkus ext add quarkus-reactive-pg-client quarkus-resteasy-reactive quarkus-hibernate-reactive-panache quarkus-resteasy-reactive-jackson

Just change the GreetingResource to:
```
import io.smallrye.mutiny.Uni
import io.smallrye.mutiny.coroutines.awaitSuspending
import javax.ws.rs.GET
import javax.ws.rs.Path
import javax.ws.rs.Produces
import javax.ws.rs.core.MediaType

@Path("/hello")
class GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    suspend fun hello(): String? {
        val uni = Uni.createFrom().item { "Hellooo" }

        return uni.awaitSuspending()
    }
}
```

**Comment by manovotn** [comment]
Hi and thanks for the report.

From the error, it looks like the `LifecycleManager` is automatically removed in Quarkus because it is not explicitly injected anywhere and is only resolved dynamically. It should be marked as `@Unremovable`.
However, `@Unremovable` is a Quarkus annotation, so we would have to add it programmatically in an extension I suppose.

In other words, this will likely need to be resolved on Quarkus side but don't worry, I will create an issue there, link them and look into it, most likely on Mon :)

**Comment by TiomanGally** [comment]
Awesome. Thank you very much! :)

**Comment by manovotn** [comment]
@TiomanGally BTW you can bypass this error by making sure this bean is not removed via `application.properties`.
Just add this line:
 > quarkus.arc.unremovable-types=io.smallrye.context.jta.context.propagation.JtaContextProvider$LifecycleManager

This is decribed in here - https://quarkus.io/guides/cdi-reference#eliminate_false_positives

One more question though, how would your code look in just Java? I wanted to try that (because I am more familiar with it and wanted to make sure it works both variants) but I was unable to get the Java version to actually throw an error at all.

**Comment by manovotn** [comment]
Actually, the change I was thinking about is already in Quarkus and has been for a while, see [this code](https://github.com/quarkusio/quarkus/blob/main/extensions/narayana-jta/deployment/src/main/java/io/quarkus/narayana/jta/deployment/NarayanaJtaProcessor.java#L149-L150).

So the problem lies somewhere else, likely `quarkus-narayna-jta` deployment processor doesn't get included for some reason.
Although I'd expect hibernate-orm to include this as well, at least according to [this pom file](https://github.com/quarkusio/quarkus/blob/main/extensions/hibernate-orm/deployment/pom.xml#L24-L27).

@Sanne @gsmet any ideas what might be going wrong here?

**Comment by manovotn** [comment]
@TiomanGally, so I did some more digging and found out that the message you are seeing is basically a logging noise.
There is no impact on functionality.

You are using context propagation which attempts to propagate all known contexts and that includes transactions (JTA).
This is why you see the [`JTAContextProvider`](https://github.com/smallrye/smallrye-context-propagation/blob/main/jta/src/main/java/io/smallrye/context/jta/context/propagation/JtaContextProvider.java) trying to do something.
However, you are not using Narayana (Quarkus JTA impl) which is why `quarkus-narayna-jta` extension isn't present and the `LifecycleManager` bean is therefore removed by Quarkus automatically. However, this doesn't really matter because `JTAContextProvider` should just return `null` (which it does) as there is ultimately nothing to propagate in terms of JTA.

And according to [this comment in `JtaContextProvider`](https://github.com/smallrye/smallrye-context-propagation/blob/main/jta/src/main/java/io/smallrye/context/jta/context/propagation/JtaContextProvider.java#L123), I guess we bumped into similar scenario earlier as well although I do not recall it.

The logging you see is basically Quarkus trying to be helpful by telling whoever performs dynamic resolution that while there is no bean meeting their requirements now, there would have been one or more if Quarkus didn't remove it.

**Comment by manovotn** [comment]
@TiomanGally after a discussion with colleagues, we surmised that this might be an error in how the application is generated for Gradle in that some of the deps shouldn't be present which would also make the warning go away.

I have created a Quarkus issue to track this, keep an eye on https://github.com/quarkusio/quarkus/issues/25454 if you want to track the progress. I'll close this issue.

In the meantime, you can workaround the warning by using the [suggestion I mentioned earlier](https://github.com/smallrye/smallrye-context-propagation/issues/363#issuecomment-1120019756).
