### ISSUE TITLE
The dispose method never gets called

### ISSUE THREAD

**Issue by DavideD** [smallrye/smallrye-context-propagation#375]
This is more a question than an issue.

Maybe I'm missing something, but it seems that the dispose method in CDI never gets called.
I've tested this by throwing an exception in [EntityManagerProvider](https://github.com/DavideD/smallrye-context-propagation/commit/ec5b8985038477045def5561c37211587c02c21b).

Also, why [this test expects an error when calling the async method](https://github.com/smallrye/smallrye-context-propagation/blob/b577ac4e196ceb4842e529894d93704062509f9c/tests/src/test/java/io/smallrye/context/test/FullStackTest.java#L181)?

**Comment by manovotn** [comment]
Hi,

those are good questions.

> Maybe I'm missing something, but it seems that the dispose method in CDI never gets called.

The tests in this repo use Weld underneath (which Quarkus for instance doesn't) and the reason might be this - https://docs.jboss.org/weld/reference/latest/en-US/html_single/#_pitfalls_and_drawbacks
The propagation in Weld basically takes the set of beans and puts them into a newly created context on a given thread which means several threads could possibly try to end that context and trigger disposal. That's why the [`CDIContextProvider`](https://github.com/smallrye/smallrye-context-propagation/blob/main/cdi/src/main/java/io/smallrye/context/cdi/context/propagation/CdiContextProvider.java) avoids invalidating contexts and just deactivates them.

Now, in Quarkus, this would work differently because the propagation can be done in a better way with Arc (CDI Impl) than with Weld and whole bean storage is propagated instead.

That being said, the test seems incorrect in relying on this behavior but it doesn't seem to affect the test logic itself.

> Also, why [this test expects an error when calling the async method](https://github.com/smallrye/smallrye-context-propagation/blob/b577ac4e196ceb4842e529894d93704062509f9c/tests/src/test/java/io/smallrye/context/test/FullStackTest.java#L181)?

I'd say because compared to the `async-working` endpoint, it doesn't perform [this context capture](https://github.com/smallrye/smallrye-context-propagation/blob/b577ac4e196ceb4842e529894d93704062509f9c/tests/src/main/java/io/smallrye/context/test/FullStackResource.java#L102).

**Comment by DavideD** [comment]
> That being said, the test seems incorrect in relying on this behavior but it doesn't seem to affect the test logic itself.

A comment in the method would help. Or throwing an `AssertionException`. It would make it clearer that's expected.

> I'd say because compared to the async-working endpoint, it doesn't perform [this context capture](https://github.com/smallrye/smallrye-context-propagation/blob/b577ac4e196ceb4842e529894d93704062509f9c/tests/src/main/java/io/smallrye/context/test/FullStackResource.java#L102).

Ah, one it's call `async-working` because it's expected to work... ok...

**Comment by DavideD** [comment]
Thanks

**Comment by manovotn** [comment]
> A comment in the method would help. Or throwing an AssertionException. It would make it clearer that's expected.

I agree, The disposal logic should be moved elsewhere too although I am not sure where because this one is a natural fit under normal circumstances.
I've created https://github.com/smallrye/smallrye-context-propagation/issues/376 so as not to forget this (as I cannot tend to it right away).
