### ISSUE TITLE
Tests fail in CI

### ISSUE THREAD

**Issue by FroMage** [smallrye/smallrye-context-propagation#46]
@manovotn can you see the CI logs? Master current fails and I wonder if it's to do with CDI?

https://semaphoreci.com/smallrye/smallrye-context-propagation/branches/master/builds/47

**Comment by manovotn** [comment]
@FroMage two notable things I can see there.

Firstly, there is an error from Weld but points to a producer method in `EntityManagerProvider` which is used in `FullStackTest`. What it complains about it that you are using contextual reference after you shutdown Weld container (which I am not aware we would do there?).

>END: true TransactionImple < ac, BasicAction: 0:ffff0a0003ad:a9d0:5ca22534:19 status: ActionStatus.RUNNING >
org.jboss.weld.exceptions.IllegalStateException: WELD-000229: Contextual reference of Producer Method [TransactionManager] with qualifiers [@Any @Default] declared as [[BackedAnnotatedMethod] @Produces @ApplicationScoped public io.smallrye.context.test.EntityManagerProvider.transactionManager()] is not valid after container fd5e9692-854f-4eeb-8211-2898293695b6 shutdown

Both, in CI and locally, the last lines I actually see are:
>Disposing EM
Got exception: java.util.concurrent.CompletionException: java.lang.NullPointerException

It's weird that I cannot reproduce the (`WELD-000229`) exception locally and weirder still that even in CI the test then actually passes even though the NPE is shown every time?!

Secondary issue, the CI failure itself, seems to be timeout on `CdiContextPropagatesTest`.
The test used `CountdownLatch` but in what should be [safe manner (with upper bound on waiting)](https://github.com/smallrye/smallrye-context-propagation/blob/master/tests/src/test/java/io/smallrye/context/test/cdi/context/propagation/CdiContextPropagatesTest.java#L47), so I don't really see where it hangs. Again, locally this passes every single time. And below this test, I can see loads of `ARJUNA` logging which doesn't fit either, because that CDI test doesn't use anything from Arjuna at all.

**Comment by FroMage** [comment]
Mmm… perhaps the NPE can help me debug it locally. Thanks.

**Comment by FroMage** [comment]
The full stack trace of the NPE is:

```
	at org.jboss.weld.contexts.AbstractBoundContext.deactivate(AbstractBoundContext.java:80)
	at org.jboss.weld.contexts.bound.BoundRequestContextImpl.deactivate(BoundRequestContextImpl.java:49)
	at io.smallrye.context.cdi.context.propagation.CdiContextProvider.lambda$1(CdiContextProvider.java:103)
	at io.smallrye.context.cdi.context.propagation.CdiContextProvider$$Lambda$280/1721974402.endContext(Unknown Source)
	at io.smallrye.context.ActiveContextState.endContext(ActiveContextState.java:26)
	at io.smallrye.context.impl.ThreadContextImpl$ContextualBiConsumer.accept(ThreadContextImpl.java:157)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.smallrye.context.test.FullStackResource.lambda$2(FullStackResource.java:180)
	at io.smallrye.context.test.FullStackResource$$Lambda$229/513569832.handle(Unknown Source)
	at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:286)
	at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:273)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:251)
	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:69)
	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:32)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:248)
	at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:258)
	at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:219)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$2(HttpContext.java:342)
	at io.vertx.ext.web.client.impl.HttpContext$$Lambda$263/2085151518.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.vertx.core.impl.EventLoopContext$$Lambda$140/1589968642.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

so `getBeanStore()` is `null`. It appears we're ending the context before the response is sent.

**Comment by FroMage** [comment]
Oh I know what happens: we return a `CS` which has context propagation to the container. The container registers a listener on it to be notified when it's ready. When it's ready, the container is notified of the return value BUT we also restored context for it, and then once the container is notified, it will clean up the request contexts, and then our context propagation will try to end the context.

Wow. Not sure how to fix this.

**Comment by manovotn** [comment]
So we are trying to deactivate the same context twice?

**Comment by FroMage** [comment]
Yes: the container terminates the context (as it should), and then because the container is notified in a CS with context propagation, we cleanup the context propagation, but it's dead.

**Comment by FroMage** [comment]
As for `CdiContextPropagatesTest` it starts Hibernate for some reason. Probably the other tests interfere.

**Comment by manovotn** [comment]
What exactly do you mean by container?
I mean, if it's the `CdiContextProvider` giving headaches, we could improve that by adding a check to whether the context is still active. The [cleanup phase of this provider](https://github.com/smallrye/smallrye-context-propagation/blob/master/cdi/src/main/java/io/smallrye/context/cdi/context/propagation/CdiContextProvider.java#L100-L110) doesn't account for anyone else playing context activation tricks on it. It just goes and deactivates what it previously activated because we want to make sure we clean up and no contexts are left hanging...

**Comment by FroMage** [comment]
> What exactly do you mean by container?

The HTTP container which sets up and terminates the request context.

**Comment by manovotn** [comment]
Each CDI `Context` has `isActive()` method, so you can try that before you `deactivate()`.
Nonetheless, there is no guarantee someone won't end the context in between invocation of these two methods - that's why juggling with context activation from several places is dangerous :-/

**Comment by FroMage** [comment]
Well, if the container does not terminate the request context, who will? It's not like we have a choice.

**Comment by FroMage** [comment]
I've bumped the timeout for CI because loading Hibernate (by accident) makes it take too much time on the CI server. I think that's why our CI builds failed. Though there's at least one javadoc issue as well.

**Comment by FroMage** [comment]
As for the container issue. The proper solution would be to not enable context propagation when the container registers for the user-returned CS. Except I'm not sure if some listeners depend on having that context or not.

**Comment by FroMage** [comment]
WOOHOO the tests finally pass!

**Comment by manovotn** [comment]
Yeah, that's the check I meant earlier :)

Though I think there might be different hidden problem, I don't really understand why you need to deactivate the context via container when `CdiContextProvider` apparently tried to do just that. It's also weird that `CdiContextProvider` doesn't battle container over activation of contexts in the first place?

`CdiContextProvider` has [detection for running contexts](https://github.com/smallrye/smallrye-context-propagation/blob/master/cdi/src/main/java/io/smallrye/context/cdi/context/propagation/CdiContextProvider.java#L61) and based on that goes through a branch where it is responsible for context activation, yet here it doesn't do deactivation?!

**Comment by FroMage** [comment]
Well, the container has to set up and tear down request contexts, no? That's their job, because they're the only ones who know when a request starts and terminates. That's how it works in RESTEasy and that's how it works in Quarkus. I expect the same to be true for all container, no?

**Comment by manovotn** [comment]
@FroMage So after loads of `System.out`s, I think that the actual problem is in `FullStackTest` itself.

Namely I think you needn't terminate the contexts [here](https://github.com/smallrye/smallrye-context-propagation/blob/master/tests/src/test/java/io/smallrye/context/test/FullStackTest.java#L128) because this code is actually wrapped *inside* context propagation itself which will attempt to deactivate the context. Besides, you are not the one who activated it on that thread in the first place (`CdiContextProvider` did).

What I am not sure about is who (if anyone) actually ends the context on the previous (main thread)?

**Comment by FroMage** [comment]
It's dissociated from the main thread here: https://github.com/smallrye/smallrye-context-propagation/blob/master/tests/src/test/java/io/smallrye/context/test/FullStackTest.java#L106

But generally it's really the container's responsability to terminate contexts. CDI or not. Context propagation does not terminate contexts, it only saves/propagates them, but not destroy them.

**Comment by manovotn** [comment]
To answer myself, nobody because it all takes place on vertx event loop where the context propagation is, so main thread is actually untouched here. In that case I think the invocation of `terminateContext()` is simply superfluous.

**Comment by manovotn** [comment]
It destroys them so long as it activated them which is correct and which isn't happening here.
In this case CDI context  provider was allowed to activate them, but before the whole wrapped task was done, it as actually deactivated.

**Comment by FroMage** [comment]
Deactivating is not the same as destroying, surely? Only the container knows when a request is over and should be terminated and the transaction committed/rolled-back, etc…

**Comment by manovotn** [comment]
Yes, I am talking purely CDI context here, the word context is truly overloaded here :)
If you don't handle the TX part, you get the hang in tests.
